# Site settings
title: Conscience Alchemy
description: "A blog about Conscienceness and Alchemy"
url: '/Conscience-Alchemy'
author:
  name: "Jeff Ward"
  email: "conscience-alchemy@gmail.com"
  url: '/Conscience-Alchemy'
  baseurl: '/Conscience-Alchemy' 

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.68"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
